Recipe app
codedit334/RoR_Group_Project pull request #21
Opened 2023-06-29 16:15 UTC by codedit334

# Hey Reviewer 👋,

This project is made by @codedit334 and  @Gmanlove 

Tasks done in this project:
- Group work:
  - #1 
- @codedit334 's work:  
  - #2 
  - #4 
  - #6 
  - #9 
  - #7
- @Gmanlove 's work:
  - #3 
  - #5 
  - #8 
  - #11

# ✋

2023-06-29 18:43 UTC, cynthiainga requested changes
Hi @codedit334 & @Gmanlove, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights

- [ ] Follow the GitHub flow and Gitflow ✔️ 
- [ ] The app work as expected ✔️ 
- [ ] Associations are setup correctly ✔️ 
- [ ] Good commit history ✔️ 

## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇🏾 👇🏾 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-29 18:43 UTC, cynthiainga commented on app/views/general_shopping_lists/index.html.erb
> +</table>
- [ ] As mentioned in the project requirement you should match the given wireframe, kindly make sure this page much the provided design 🙃 

Your design

<img width="646" alt="Screenshot 2023-06-29 at 20 39 08" src="https://github.com/codedit334/RoR_Group_Project/assets/74501523/6ca03cf4-10ab-4549-b0ad-ad32e9feb223">

Given wireframe

<img width="1024" alt="Screenshot 2023-06-29 at 20 39 40" src="https://github.com/codedit334/RoR_Group_Project/assets/74501523/fe162ae1-4044-4175-8d92-ca5c25bf9412">

- [optional] Also I would suggest you to the `Hello #username` before the navigation bar 😁

2023-06-29 18:43 UTC, cynthiainga commented on README.md
> +  This project is [MIT](./LICENSE.txt) licensed.
- [ ] Please kindly fix your MIT link license, it is direct to the page not found 🙃

2023-06-29 18:43 UTC, cynthiainga commented on README.md
> +**[Catalog of my things]** Blog App is a web application that allows users to create, read, update, and delete blog posts. Users can sign up for an account, create new blog posts, and edit or delete
- [ ] Please kindly update the description of your project and the title as well 🙏🏾

2023-06-29 18:43 UTC, cynthiainga commented on README.md
> +
- [ ] Kindly update your `Key Feature` as well, this project is about Recipe and food not post comment or like 😁

2023-06-29 18:43 UTC, cynthiainga commented on README.md
> + git clone https://github.com/ernestmusong/Blog-app.git
- [ ] Kindly add the correct link to clone 🙃

2023-06-29 18:43 UTC, cynthiainga commented on README.md
> +
- [OPTIONAL] It would be better if the other author add more contact information like LinkedIn and twitter 😁

2023-06-29 18:43 UTC, cynthiainga commented on README.md
> +
- [ ] Please kindly update your Future Features to correspond the project 🙃

2023-06-29 18:43 UTC, cynthiainga commented on README.md
> +Feel free to check the [issues page](https://github.com/ernestmusong/Blog-app/issues).
- [ ] When I click to the issue link it direct me to another project `Blog-app` please kindly fix that 🙏🏾

2023-06-30 11:07 UTC, prolajumokeoni approved these changes
Hi @codedit334 and @Gmanlove 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- Good App design 💪🏿
- All changes requested have been implemented 🥇  


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-30 11:08 UTC, codedit334 commented
Thanks @prolajumokeoni !

2023-06-30 11:08 UTC, merged

2023-06-30 11:45 UTC, Gmanlove commented
Thanks for your  time